dist: xenial
sudo: required
language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
before_install:
  - sudo add-apt-repository ppa:named-data/ppa -y
  - sudo apt-get update -q
  - sudo apt-get install nfd -y
install:
  - pip install -r requirements.txt
before_script:
  - git clone --depth=1 --single-branch https://github.com/named-data/PyNDN2 $HOME/PyNDN2
  - export PYTHONPATH=$HOME/PyNDN2/python:$(pwd)/python
script:
  - pytest --ignore examples/
