# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: content-meta-info.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='content-meta-info.proto',
  package='ndn_message',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x17\x63ontent-meta-info.proto\x12\x0bndn_message\"\xce\x01\n\x16\x43ontentMetaInfoMessage\x12O\n\x11\x63ontent_meta_info\x18\x80\x01 \x02(\x0b\x32\x33.ndn_message.ContentMetaInfoMessage.ContentMetaInfo\x1a\x63\n\x0f\x43ontentMetaInfo\x12\x15\n\x0c\x63ontent_type\x18\x81\x01 \x02(\t\x12\x12\n\ttimestamp\x18\x82\x01 \x02(\x04\x12\x15\n\x0chas_segments\x18\x83\x01 \x02(\x08\x12\x0e\n\x05other\x18\x84\x01 \x01(\x0c')
)




_CONTENTMETAINFOMESSAGE_CONTENTMETAINFO = _descriptor.Descriptor(
  name='ContentMetaInfo',
  full_name='ndn_message.ContentMetaInfoMessage.ContentMetaInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='content_type', full_name='ndn_message.ContentMetaInfoMessage.ContentMetaInfo.content_type', index=0,
      number=129, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='ndn_message.ContentMetaInfoMessage.ContentMetaInfo.timestamp', index=1,
      number=130, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='has_segments', full_name='ndn_message.ContentMetaInfoMessage.ContentMetaInfo.has_segments', index=2,
      number=131, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='other', full_name='ndn_message.ContentMetaInfoMessage.ContentMetaInfo.other', index=3,
      number=132, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=148,
  serialized_end=247,
)

_CONTENTMETAINFOMESSAGE = _descriptor.Descriptor(
  name='ContentMetaInfoMessage',
  full_name='ndn_message.ContentMetaInfoMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='content_meta_info', full_name='ndn_message.ContentMetaInfoMessage.content_meta_info', index=0,
      number=128, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_CONTENTMETAINFOMESSAGE_CONTENTMETAINFO, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=41,
  serialized_end=247,
)

_CONTENTMETAINFOMESSAGE_CONTENTMETAINFO.containing_type = _CONTENTMETAINFOMESSAGE
_CONTENTMETAINFOMESSAGE.fields_by_name['content_meta_info'].message_type = _CONTENTMETAINFOMESSAGE_CONTENTMETAINFO
DESCRIPTOR.message_types_by_name['ContentMetaInfoMessage'] = _CONTENTMETAINFOMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ContentMetaInfoMessage = _reflection.GeneratedProtocolMessageType('ContentMetaInfoMessage', (_message.Message,), dict(

  ContentMetaInfo = _reflection.GeneratedProtocolMessageType('ContentMetaInfo', (_message.Message,), dict(
    DESCRIPTOR = _CONTENTMETAINFOMESSAGE_CONTENTMETAINFO,
    __module__ = 'content_meta_info_pb2'
    # @@protoc_insertion_point(class_scope:ndn_message.ContentMetaInfoMessage.ContentMetaInfo)
    ))
  ,
  DESCRIPTOR = _CONTENTMETAINFOMESSAGE,
  __module__ = 'content_meta_info_pb2'
  # @@protoc_insertion_point(class_scope:ndn_message.ContentMetaInfoMessage)
  ))
_sym_db.RegisterMessage(ContentMetaInfoMessage)
_sym_db.RegisterMessage(ContentMetaInfoMessage.ContentMetaInfo)


# @@protoc_insertion_point(module_scope)
